# Generated by Django 4.1 on 2022-09-20 09:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0002_region_alter_drama_region'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='drama',
            options={},
        ),
    ]
