# Generated by Django 4.1 on 2022-09-20 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0006_alter_user_avatar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='drama',
            name='img_cover',
            field=models.ImageField(blank=True, default=None, upload_to='tracker/static/tracker/img/cover'),
        ),
        migrations.AlterField(
            model_name='drama',
            name='img_small',
            field=models.ImageField(blank=True, default=None, upload_to='tracker/static/tracker/img/small'),
        ),
        migrations.AlterField(
            model_name='user',
            name='avatar',
            field=models.ImageField(blank=True, default='tracker/static/tracker/img/avatar/default.webp', null=True, upload_to='tracker/static/tracker/img/avatar'),
        ),
    ]
