# Generated by Django 4.1 on 2022-09-20 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0007_alter_drama_img_cover_alter_drama_img_small_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='avatar',
            field=models.ImageField(blank=True, default='default.webp', null=True, upload_to='tracker/static/tracker/img/avatar'),
        ),
    ]
