# Generated by Django 4.1 on 2022-09-20 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0008_alter_user_avatar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='avatar',
            field=models.ImageField(blank=True, default='tracker/static/tracker/img/avatar/default.jpg', null=True, upload_to='tracker/static/tracker/img/avatar'),
        ),
    ]
