# Generated by Django 4.1 on 2022-09-22 07:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0009_alter_user_avatar'),
    ]

    operations = [
        migrations.CreateModel(
            name='Actor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first', models.CharField(max_length=64)),
                ('middle', models.CharField(blank=True, max_length=64)),
                ('last', models.CharField(max_length=64)),
                ('drama', models.ManyToManyField(blank=True, related_name='actors', to='tracker.drama')),
            ],
        ),
    ]
