# Generated by Django 4.1 on 2022-09-22 08:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0011_remove_drama_genre_genre_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='genre',
            name='category',
        ),
        migrations.AddField(
            model_name='drama',
            name='category',
            field=models.ManyToManyField(blank=True, related_name='categories', to='tracker.genre'),
        ),
    ]
