# Generated by Django 4.1 on 2022-09-22 08:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0014_category_alter_genre_genre'),
    ]

    operations = [
        migrations.AddField(
            model_name='drama',
            name='category',
            field=models.ManyToManyField(blank=True, related_name='categories', to='tracker.category'),
        ),
    ]
