# Generated by Django 4.1 on 2022-09-22 08:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0015_drama_category'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Genre',
        ),
    ]
