# Generated by Django 4.1 on 2022-09-22 08:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0016_delete_genre'),
    ]

    operations = [
        migrations.AddField(
            model_name='drama',
            name='genre',
            field=models.ForeignKey(blank=True, default=None, on_delete=django.db.models.deletion.CASCADE, related_name='genres', to='tracker.category'),
        ),
    ]
