# Generated by Django 4.1 on 2022-09-22 12:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0017_drama_genre'),
    ]

    operations = [
        migrations.AddField(
            model_name='actor',
            name='profile',
            field=models.URLField(blank=True),
        ),
    ]
