# Generated by Django 4.1 on 2022-09-22 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0018_actor_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='actor',
            name='role',
            field=models.CharField(blank=True, max_length=64),
        ),
    ]
