# Generated by Django 4.1 on 2022-09-23 12:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0020_watchlist'),
    ]

    operations = [
        migrations.CreateModel(
            name='Favorite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=64, null=True)),
                ('favdrama', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='tracker.drama')),
            ],
        ),
    ]
