# Generated by Django 4.1 on 2022-09-23 13:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0021_favorite'),
    ]

    operations = [
        migrations.AddField(
            model_name='actor',
            name='nationality',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='tracker.region'),
        ),
    ]
