# Generated by Django 4.1 on 2022-10-07 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0022_actor_nationality'),
    ]

    operations = [
        migrations.AddField(
            model_name='drama',
            name='link_trailer',
            field=models.URLField(blank=True),
        ),
    ]
