# Generated by Django 4.1 on 2022-10-10 08:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0023_drama_link_trailer'),
    ]

    operations = [
        migrations.CreateModel(
            name='Upcoming',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('d_link_img', models.URLField(blank=True)),
                ('d_total_episode', models.IntegerField()),
                ('d_region', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='d_select_region', to='tracker.region')),
            ],
        ),
    ]
