# Generated by Django 4.1 on 2022-10-11 12:35

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0025_upcoming_d_date_upcoming_d_title'),
    ]

    operations = [
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('drama_name', models.IntegerField(null=True)),
                ('ratings', models.IntegerField(null=True)),
                ('username', models.CharField(max_length=64, null=True)),
                ('comment', models.TextField(null=True)),
                ('date', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
            ],
        ),
    ]
