# Generated by Django 4.1 on 2022-10-11 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0026_review'),
    ]

    operations = [
        migrations.RenameField(
            model_name='review',
            old_name='comment',
            new_name='review',
        ),
        migrations.AlterField(
            model_name='review',
            name='drama_name',
            field=models.CharField(max_length=64, null=True),
        ),
    ]
