# Generated by Django 4.1 on 2022-10-11 14:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0027_rename_comment_review_review_alter_review_drama_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='review',
            old_name='date',
            new_name='r_date',
        ),
    ]
